# Generated by Django 5.2.5 on 2025-08-19 13:16

from django.db import migrations

def seed_data(apps, schema_editor):
    Author = apps.get_model("myapp", "Author")
    Author.objects.create(name="Hehe", email="hehe@example.com")

def remove_seed_data(apps, schema_editor):
    Author = apps.get_model("myapp", "Author")
    Author.objects.filter(name="Hehe", email="hehe@example.com").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(seed_data),
         migrations.RunPython(seed_data, remove_seed_data),
    ]
